version: 0.2

phases:
  install:
    commands:
      - n 19.9.0
      - node --version
      - npm i npm@10.2.5 -g
      - npm --version
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - echo Build Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync dist/ $S3_BUCKET
